project:
  type: website

website:
  title: "notebooks2"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kameyama
      - icon: twitter
        href: https://twitter.com/kamesen
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  open-graph: true  
  google-analytics: "G-3B1NXS7X3W"

format:
  html:
    theme: cyborg
    css: styles.css

execute:
  freeze: auto

comments:
  hypothesis: true
