project:
  type: website

website:
  title: "notebooks2"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  google-analytics: "G-3B1NXS7X3W"
format:
  html:
    theme: cyborg
    css: styles.css



