on:
  push:
    branches: main

name: Render and Publish

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:2.9
    steps:
      - uses: actions/checkout@master
      - run: mkdir $(pwd)/_site/posts
      - run: ls org | sed 's/\..*//' | xargs -IXXX pandoc --standalone -f org -t html $(pwd)/org/XXX.org -o $(pwd)/_site/posts/XXX.html
          
  build-deploy:
    needs: convert_via_pandoc
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
        #  path: source-folder # By default, the current working dir is used i.e `quarto render .
      # add software dependencies here

      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      
      # - name: Publish to Netlify (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      # - name: Publish to RStudio Connect (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: connect
      #     CONNECT_SERVER: enter-the-server-url-here
      #     CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }} 

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
