on:
  push:
    branches: main

name: Render and Publish

jobs:  
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      # add software dependencies here

      - name: Convert org to markdown via Pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc
          ls
          ls org | sed 's/\..*//' | xargs -IXXX pandoc --standalone -f org -t markdown org/XXX.org -o posts/XXX.qmd --lua-filter ./convert_categories_in_org_metadata.lua
              
      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      
      # - name: Publish to Netlify (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      # - name: Publish to RStudio Connect (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: connect
      #     CONNECT_SERVER: enter-the-server-url-here
      #     CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }} 

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
